---
title: "la_ easing_restriction"
author: "Melody Ma"
date: "4/19/2021"
output: html_document
---

1. import libraries and and dataset - no need to change
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(readr)
library(ggseas)
library(chron)
library(plotly)
library(zoo)
```

```{r}
data <- read_csv("../../data/cleaned/NPI_cases_04162021.csv") %>% 
  select(c("STATE", "DATE", "NEWCONFIRMED", "EVENT_CATG_S",
           "SCORE", "SHORT_DESCRIPT"))

state_pop_dt <- read_csv("../../data/cleaned/USA_States_Data.csv") %>% 
  select(c("STATE_NAME", "POPULATION"))
# change state population data state_name to all caps
state_pop_dt$STATE_NAME <- toupper(state_pop_dt$STATE_NAME)

# change column names
colnames(data) <- c("State", "Date", "New_Confirmed", "Event_Catg_S","Score", "Short_Description")
colnames(state_pop_dt) <- c("State", "Population")

# join covid and population data
data <- inner_join(data, state_pop_dt, by=c("State")) 
data$Date <- as.Date(data$Date, format="%m/%d/%Y")

data$`New Cases/500,000 ppl`<-
  round(data$New_Confirmed/(data$Population/500000))

```



```{r}
# change event code to description
group_event_catg <- function(x){
  new_col = c()
  check = substr(x, nchar(x), nchar(x))
  if(check %in% c("M", "R")){
    new_col <- append(new_col, "Restricting")
  } else if (check %in% c("E", "L")){
    new_col <- append(new_col, "Easing")
  } else {
    new_col <- append(new_col, x)
  }
}

data$event_MELR <- sapply(data$Event_Catg_S, FUN=group_event_catg)

# category num
big_catg <- function(x){
  new_col = c()
  if (is.na(x)){
    new_col <- append(new_col, x)
  } 
  else if(x=="15M"){
    new_col <- append(new_col, "Face Covering")
  } else if(grepl("2", x)){
    new_col <- append(new_col, "Business Restrictions")
  } else if(grepl("3", x)){
    new_col <- append(new_col, "Indoor Gathering Restrictions")
  } else if(grepl("4", x)){
    new_col <- append(new_col, "Restaurant/Bar Restrictions")
  } else{
    new_col <- append(new_col, "Stay at Home Orders")
  }
}

data$big_cat <- sapply(data$Event_Catg_S, FUN=big_catg)
data$event <- paste(data$big_cat, "\n", data$event_MELR)


```


```{r}

gplot_lag <- function(state, lead_n, window_num){
  state_data <- data[data$State==state,]
  state_data = state_data[!is.na(state_data$New_Confirmed),]
  identity_x <- seq(0, max(na.omit(state_data$`New Cases/500,000 ppl`)),
                    by=1)
  identity_y <- identity_x

  corr <- round(acf(na.omit(state_data$`New Cases/500,000 ppl`),
                               lag.max=lead_n, 
              plot=FALSE)[lead_n]$acf[1], digits=2)
  state_data$`New Cases/500,000 ppl` = 
    round(rollmean(state_data$`New Cases/500,000 ppl`, window_num,
             fill=NA))
  state_data$n_lead = rep(NA, nrow(state_data))
  for (i in 1:(nrow(state_data)-lead_n)){
    today = state_data[i, "Date"]
    n_day_after = today+lead_n
    inst = state_data[as.character(state_data$Date)==as.character(n_day_after[1,1]),]
    state_data$n_lead[i] = inst$`New Cases/500,000 ppl`
  }
  
  plot <- ggplot(data=state_data)+
     geom_point(aes(x=`New Cases/500,000 ppl`, y=n_lead,
                   col=as.factor(event_MELR)),
                   # text=paste("Date of x-axis:", DATE,
                   #            "\nDate of y-axis:", DATE+lead_n,
                   #            "\nEvent:", event)), 
               size=2.5, alpha = 0.8)+
    scale_color_manual(values=c("#DD3D2D","#1965B0","white"),name="Event Category",
                        labels=c("Easing", "Restricting",""))+
    scale_alpha_manual(values=c(1,1,0))+
   
    geom_line(data=data.frame(identity_x, identity_y),
              aes(x=identity_x, y=identity_y), linetype="dotted", size=1)+
   
    labs(title=paste(str_to_title(state),"lag", lead_n, "correlation=", corr), 
         x="Today's Norm New Confirmed Cases",
         y=paste("Normalized New Daily Cases", lead_n, "days later"),
         col = "Event_Category")
  
  plot
}
```


```{r}
state = toupper("Michigan")
lag_day = 35

window_num = 7

p <- gplot_lag(state, lag_day, window_num) #function to plot - no need to change
p

p + scale_x_continuous( limits=c(0, 450)) +
  scale_y_continuous(limits=c(0, 450)) + 
  theme_bw()

```

