1. import libraries and and dataset - no need to change
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(ggplot2)
library(dplyr)
library(ggseas)
library(chron)
library(ggrepel)
library(stringr)

# read and select data
data <- read_csv("../../data/cleaned/NPI_cases_12102021.csv") %>% 
  dplyr::select(c("STATE", "DATE", "NEWCONFIRMED", "EVENT_CATG_S",
           "SCORE"))
data$DATE <- as.Date(data$DATE, format="%m/%d/%y")
data <- data %>%
  filter(DATE > "2020-02-29" & DATE<="2021-03-31")
state_pop_dt <- read_csv("../../data/cleaned/USA_States_Data.csv") %>% 
  dplyr::select(c("STATE_NAME", "POPULATION"))
```


2. preprocess data - no need to change
```{r}
# join population and covid data
# change state population data state_name to all caps
state_pop_dt$STATE_NAME <- toupper(state_pop_dt$STATE_NAME)

# change column names
colnames(data) <- c("State", "Date", "New_Confirmed", "Event_Catg_S","Score", "Short_Description")
colnames(state_pop_dt) <- c("State", "Population")

# join covid and populaton data
data <- inner_join(data, state_pop_dt, by=c("State")) 
data$Date <- as.Date(data$Date, format="%m/%d/%Y")

#rescale data into 500 normalized
data$`New Cases/500,000 ppl`<-
  round(data$New_Confirmed/(data$Population/500000))

# add score line
data$dummy <- -30

# relabel events in business, gathering, restaurant&bar categories
relabel_event <- function(x){
  new_col = c()
  if (is.na(x)){
    new_col <- append(new_col, x)
  } else if(x %in% c("2R", "2SM")){
    new_col <- append(new_col, "B-R")
  } else if (x %in% c("2E", "2L")){
    new_col <- append(new_col, "B-E")
  } else if (x %in% c("2E", "2L")){
    new_col <- append(new_col, "Eased")
  } else if (x %in% c("3M", "3R", "3SM", "3SR", "3I")){
    new_col <- append(new_col, "GL-R")
  } else if (x %in% c("3E", "3L")){
    new_col <- append(new_col, "GL-E")
  } else if (x %in% c("4A", "4R", "4SM")){
    new_col <- append(new_col, "RB-R")
  } else if (x %in% c("4E", "4L")){
    new_col <- append(new_col, "RB-E")
  } else {
    new_col <- append(new_col, NA)
  }
}
data$Event <- sapply(data$Event_Catg_S, FUN=relabel_event)

# remove rows if date is NA
data <- data[!is.na(data$Date),]
# add a new column for vaccine, labor day, mask mandate
relabel_event2 <- function(x){
  new_col = c()
  if (x=="2020-09-07"){
    append(new_col, "Labor Day")
  } else if (x=="2020-12-11"){
    append(new_col, "Pfizer")
  } else if (x=="2021-02-27"){
    append(new_col, "Janssen")
  } else if (x=="2020-12-18"){
    append(new_col, "Moderna")
  } else {
    append(new_col, NA)
  }
}
data$Event2 <- sapply(data$Date, FUN=relabel_event2)

# text color bins
bins <- c(-Inf,0,0.55,1.20,1.70, 2.15,2.60,3.10,3.60,4.3, 5.00)
data$color_scale <- cut(data$Score, breaks=bins)
color_v <- c("#ffffff","#fdfec0", "#fedc9e","#fe9969","#f9765d", "#ec5761",
             "#b7377a","#5f1888","#231252","#000004") 

#data$Event <- as.factor(data$Event)
color_event_v <- c("B-R"="#FF00FF",
                   "B-E"="#008080",
                   "GL-R"="#FF00FF",
                   "GL-E"="#008080",
                   "RB-R"="#FF00FF",
                   "RB-E"="#008080",
                  "Labor\nDay"="black",
                  "Moderna"="black",
                  "Pfizer"="black",
                  "Janssen"="black")

names(color_v) = levels(data$color_scale)

# function of defining y axis
create_ypos <- function(x, ymax){
  new_col = c()
  x <- as.character(x)
  if (is.na(x)){
    new_col <- append(new_col, x)
  } else if(x%in%c("B-E","B-R")){
    new_col <- append(new_col, ymax-150)
  } else if (x%in%c("GL-E","GL-R")){
    new_col <- append(new_col, ymax-250)
  } else if (x%in%c("RB-E","RB-R")){
    new_col <- append(new_col, ymax-350)
  }
  return(new_col)
}
```



3. plot static time series function - no need to change
```{r, message=FALSE, warning=FALSE}
event_legend_labels = c("B-E: Business Restrictions Eased",
                        "B-R: Business Restrictions",
                        "GL-E: Gathering Limitation\n            Restrictions Eased",
                        "GL-R: Gathering Limitation Restrictions",
                        "RB-E: Restaurant and/or Bar\n            Restrictions Eased",
                        "RB-R: Restaurant and/or Bar\n            Restrictions",
                        "")
plot_time <- function(state, window_num, y_axis_max){
  state_data <- data[data$State==state,]
  vac <- c("Moderna","Pfizer","Janssen")
  state_data$vac <- ifelse(state_data$Event2 %in% vac,
                               state_data$Event2, NA)
  mask_index = which(state_data$Event_Catg_S=="15M")
  state_data[mask_index, "Event2"] <- "State-wide\nMask Mandate"
  mask_e_index = which(state_data$Event_Catg_S=="15L")
  state_data[mask_e_index, "Event2"] <- "State-wide\nMask Mandate Lifted"
  state_event <- state_data[(!is.na(state_data$Event_Catg_S)|
                              !is.na(state_data$Event2)),]
  state_event_date <- state_event$Date
  # get events with lines - 15M, vaccine, laborday
  state_event2 <- state_data[(!is.na(state_data$Event2))&
                               is.na(state_data$vac),]
  state_event_vac <- state_data[!is.na(state_data$vac),]
  
  # text label for events
  state_event$ypos <- sapply(state_event$Event, FUN=create_ypos,
                             y_axis_max)
  annotation <- data.frame(
    x=state_event$Date,
    y=state_event$ypos,
    label=state_event$Event,
    stringsAsFactors=FALSE
  )
  
  # add mask mandate to event2
  annotation3 <- data.frame(
    x=state_event2$Date,
    y=rep(y_axis_max-50, length.out=nrow(state_event2)),
    label=state_event2$Event2
  )
  #vaccine data separately
  annotation33 <- data.frame(
    x=state_event_vac$Date,
    y=rep(y_axis_max-100, length.out=nrow(state_event_vac)),
    label=state_event_vac$vac
  )

  stay_home_index = which(state_event$Event_Catg_S=="1SM")
  stay_home_date <-  state_event[stay_home_index, "Date"]$Date
  stay_home_end_index = which(state_event$Event_Catg_S=="1L")
  if (length(stay_home_end_index)==0){
    stay_home_end_date <- max(state_data$Date)
  } else {
    stay_home_end_date <- state_event[stay_home_end_index, "Date"]$Date
  }
  stay_home_mid <- stay_home_date + (stay_home_end_date-stay_home_date)/2
  annotation4 <- data.frame(
    x=stay_home_mid,
    y=y_axis_max-50,
    label="State-wide\nStay-at-home Order"
  )
  
  
  p <- ggplot(state_data, aes(Date, `New Cases/500,000 ppl`)) +
    annotate("rect", xmin = stay_home_date, xmax = stay_home_end_date,
         ymin = -15, ymax = y_axis_max-20, alpha = .2)+
    geom_point(size=4, alpha=1) + 
    stat_rollapplyr(width = window_num, align = "right", size = 2,
                    col="gray", alpha=1)+
    geom_point(mapping=aes(x=Date, y=dummy, fill=color_scale), shape=22,
               size=8, color="transparent")+
    scale_color_manual(values=color_event_v) +
                #   label=event_legend_labels)+
    scale_fill_manual(values=color_v)+
    geom_segment(data=annotation, aes(x=x, y=-15, xend=x,
                                      yend=as.numeric(y)-20),
                 size=0.8, alpha=0.7, col="gray")+
    geom_text_repel(data=annotation, aes(x=x, y=as.numeric(y),
                                         label=label, col=label),
                    size=8, na.rm=TRUE, direction = "x", 
                    min.segment.length=100, seed = 42)+
    geom_text_repel(data=annotation3, aes(x=x, y=as.numeric(y),
                                         label=label),
              size=8)+
    geom_text_repel(data=annotation33,
                    aes(x=x, y=y, 
                    label=label),
                    size=8, direction = "x",
                    min.segment.length=100, seed = 42, box.padding = 0.5)+
    geom_text(data=annotation4, aes(x=x, y=y, label=label),
              size=8)+
    geom_segment(data=state_event2,
               aes(x=Date, y=-15, xend=Date,
                   yend=y_axis_max-100), size=1, alpha=0.7, col="gray")+
    geom_segment(data=state_event_vac,
               aes(x=Date, y=-15, xend=Date,
                   yend=y_axis_max-135), size=1, alpha=0.7, col="gray")+
    ylim(-50, y_axis_max)+
    theme(legend.title=element_blank())+
    labs(x = "", y = "New Daily Cases per 500,000 people",
         title=(paste(str_to_title(state))))+
        # fill="Scores",
        # color="Events")+
    scale_x_date(date_breaks = "months" , date_labels = "%b") +
    theme_classic()+
    theme(axis.text=element_text(size=24),
        axis.title=element_text(size=28,face="bold"),
        title=element_text(size=30, face='bold'),
        legend.title=element_text(size=18, face='bold'),
        legend.text=element_text(size=18),
        legend.margin=margin(t = 0, unit='cm')
    )
  
  p
}

```



***** 4. modify and run this code snippet to graph static time series 
```{r, message=FALSE, warning=FALSE}
# identify which individual state
state = "MARYLAND"
# identify the window(days) for moving averages
window_num = 7
# identify the upper limit of y axis
y_axis_max = 900


# function to plog interactive time series - no need to change
plotname = paste(tolower(state)," static time series_noxlabel.pdf",sep="")
pdf(plotname, width=20, height=8)
# parameters for reference: width=1500, height=803
plot_time(state, window_num, y_axis_max)
#dev.off()

```




